apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-kubedoom-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: storaxdev/kubedoom:0.5.0
          name: kubedoom
          ports:
            - containerPort: 5900
              protocol: TCP      