apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: test-ns
type: Opaque
data:
  POSTGRES_DB: dGVzdGRhdGFiYXNl
  POSTGRES_USER: dGVzdHVzZXI=
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: test-ns
data:
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim
  namespace: test-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: test-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:10.13
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
            name: psql
          envFrom:
            - secretRef:
                name: postgresql-secret
            - configMapRef:
                name: postgresql-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-db
              subPath: data
      volumes:
        - name: postgresql-db
          persistentVolumeClaim:
            claimName: postgresql-claim
